### ISSUE TITLE
Consider putting the AutoTrain GUI to this repo

### ISSUE THREAD

**Issue by hanhou** [AllenNeuralDynamics/aind-foraging-behavior-bonsai-automatic-training#54]
Conceptually, the AutoTrain GUI can be a part of this repo instead of the task-specific GUI (like dynamic foraging). In this case,

- [ ] When called from a task-specific GUI, AutoTrain GUI receives 'subject_id' and returns 'paras', and it can sync the UIs with the MainWindow as well.
- [ ] Otherwise, the GUI can run standalone just from this repo as a browser for AutoTrainManager and CurriculumManager.

**Comment by hanhou** [comment]
However, this conflicts with the RA's desire to integrate the AutoTrain GUI into the main GUI.

**Comment by alexpiet** [comment]
This is the sort of issue we should revisit when we have a plan for a common task launcher
